services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    env_file: .env
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ${CONFIG_PATH}/metabase/data:/metabase-data
    networks:
      - app-network

networks:
  app-network:
    external: true
