services:
  vikunja-db:
    image: postgres:16-alpine
    container_name: vikunja-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${VIKUNJA_DB_NAME}
      POSTGRES_USER: ${VIKUNJA_DB_USER}
      POSTGRES_PASSWORD: ${VIKUNJA_DB_PASSWORD}
    volumes:
      - ${CONFIG_PATH}/vikunja/db:/var/lib/postgresql/data
    networks:
      - app-network

  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    restart: unless-stopped
    env_file: .env
    environment:
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DB_NAME}
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DB_USER}
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DB_PASSWORD}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_JWT_SECRET}
      VIKUNJA_SERVICE_FRONTENDURL: https://${VIKUNJA_HOSTNAME}
    volumes:
      - ${CONFIG_PATH}/vikunja/files:/app/vikunja/files
    depends_on:
      - vikunja-db
    networks:
      - app-network

networks:
  app-network:
    external: true
